### PR TITLE
Moving Patreon Button into its own component!

### PR DESCRIPTION
**Pull request by mirshko**
Needed a little bit of cleanup! 

Will clean it even more!

### CODE REVIEW

**Comment by qdot** [comment]
Thanks for this PR!

As I mentioned in the other PR, the master you were working with was way behind the branch I was on. I just brought all of the code in master up to date, so you'll probably need to rebase this. However, I didn't really touch any of the patreon button code in the other branch, so I'm hoping it should be a pretty easy resolution.

**Comment by mirshko** [comment]
@qdot rebased! If the CI passes can I merge?

**Comment by mirshko** [comment]
Sorry for the delay!

**Comment by qdot** [comment]
I went ahead and took care of the linter error, thanks for doing this! I may extract it into its own repo next, as we use it in a few apps. :D

**Pull request merged**
